### ISSUE TITLE
去除 Marked 支持

### ISSUE THREAD

**Issue by 88250** [b3log/markdown-http#1]
等 markdown-it 测试一段时间，如果很稳定的话就移除 Marked 吧。

**Comment by qichuangguo** [comment]
我按照你的配置 但是 我的solo博客还是以前的md渲染 
nohup: ignoring input

> markdown-http@2.0.0 start /usr/markdown-it/markdown-http
> node index.js

markdown-it engine is running at port: 8250

**Comment by 88250** [comment]
@qichuangguo 需要重启

**Comment by qichuangguo** [comment]
@88250 我solo 是放在tomcat 下 我重启tomcat了

**Comment by 88250** [comment]
@qichuangguo 先启动 markdown-http 再重启 solo

**Comment by qichuangguo** [comment]
@88250 是的 我是这样的流程

**Comment by 88250** [comment]
@qichuangguo 麻烦看下 solo 启动后输出的日志，里面应该会打印出目前正在使用的 md 处理器

**Comment by qichuangguo** [comment]
@88250 没有找到相关的  还有什么办法吗？

**Comment by 88250** [comment]
@qichuangguo 暂时先用内置的 flexmark，v3.4.0 发布后这块我们有做加强

**Comment by Vanessa219** [comment]
marker 留着吧。他虽然不兼容 commonmark，但是比较松散，用的人也多。

@qichuangguo solo 升级到 v3.4.0 看一下，还有问题请新开 issue
